from typing import Optional, Dict
from pydantic import BaseModel
import pandas as pd

class Event:
    """
    Base class for events.
    """
    pass

class MarketEvent(Event):
    """
    Triggered when new market data is available.
    """
    def __init__(self, time_index, symbol: str, bar: pd.Series):
        self.type = 'MARKET'
        self.time_index = time_index # Timestamp
        self.symbol = symbol
        self.bar = bar # OHLCV data for this timestamp

class SignalEvent(Event):
    """
    Generated by the Strategy/Model.
    """
    def __init__(self, symbol: str, timestamp, signal_type: str, strength: float = 1.0):
        self.type = 'SIGNAL'
        self.symbol = symbol
        self.timestamp = timestamp
        self.signal_type = signal_type # 'LONG', 'SHORT', 'EXIT'
        self.strength = strength # Confidence or Portfolio %

class OrderEvent(Event):
    """
    Generated by the Portfolio to send to Execution.
    """
    def __init__(self, symbol: str, order_type: str, quantity: int, direction: str):
        self.type = 'ORDER'
        self.symbol = symbol
        self.order_type = order_type # 'MKT', 'LMT'
        self.quantity = quantity
        self.direction = direction # 'BUY', 'SELL'

class FillEvent(Event):
    """
    Generated by ExecutionHandler when an order is filled.
    """
    def __init__(self, time_index, symbol: str, exchange: str, quantity: int, 
                 direction: str, fill_cost: float, commission: float = 0.0):
        self.type = 'FILL'
        self.time_index = time_index
        self.symbol = symbol
        self.exchange = exchange
        self.quantity = quantity
        self.direction = direction
        self.fill_cost = fill_cost # Price * Quantity? Or just Fill Price? Usually Fill Price.
                                   # Let's say fill_cost is the total cost (Price * Qty)?
                                   # No, typically fill_price is useful. 
                                   # Let's use fill_price and calculate cost in Portfolio.
        self.fill_price = fill_cost # Renaming in logic if needed, but keeping variable name flexible
        self.commission = commission
